import { chromium } from 'playwright';
const base = 'http://localhost:5174';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1400, height: 1000 } });
await page.goto(base + '/contact', { waitUntil: 'networkidle' });
const el = page.locator('.contact-hours-card');
await el.scrollIntoViewIfNeeded();
await page.waitForTimeout(400);
await el.screenshot({ path: 'check-card.png' });
await browser.close();
console.log('done');
