// The arcade's vocabulary, in one place.
//
// Difficulty used to be decided by word *length* alone, which is why "Kids"
// happily served up ABS, EGR, TPMS and CASTER: all short, none of them things
// a child has heard of. Every entry now carries the level it belongs to, so a
// mode picks words a player at that level actually knows.
//
// `words` marks answers that read as two words but are entered as one run of
// letters (WATERPUMP, TIMINGBELT). Those get a "(2 wds)" tag in the clue —
// without it the clue genuinely does not match what fits in the grid.

export type ClueLevel = "kids" | "easy" | "advanced";

export type ClueWord = {
  answer: string;
  clue: string;
  level: ClueLevel;
  words?: number;
};

// [answer, clue, level, words] — a tuple list keeps a bank this size readable.
type ClueTuple = [string, string, ClueLevel, number?];

const CLUES: ClueTuple[] = [
  /* ---------------- kids: things a child sees from the back seat ------- */
  ["TIRE", "The round rubber part that rolls on the road", "kids"],
  ["HOOD", "Lift it to see the engine", "kids"],
  ["OIL", "Slippery stuff that keeps an engine happy", "kids"],
  ["HORN", "Press the wheel to make it beep", "kids"],
  ["WHEEL", "The tire goes around this", "kids"],
  ["TRUNK", "Space in the back where the bags go", "kids"],
  ["ENGINE", "The part that makes the car go", "kids"],
  ["BRAKE", "Push this pedal to stop", "kids"],
  ["KEY", "You turn it to start the car", "kids"],
  ["SEAT", "You sit on it", "kids"],
  ["MIRROR", "Look in it to see behind you", "kids"],
  ["ROAD", "Cars drive on it", "kids"],
  ["TRUCK", "Big vehicle that carries things", "kids"],
  ["VAN", "Family ride with sliding doors", "kids"],
  ["BUS", "Big yellow ride to school", "kids"],
  ["JACK", "Tool that lifts a car off the ground", "kids"],
  ["GARAGE", "Where cars get fixed", "kids"],
  ["WIPER", "It wipes rain off the glass", "kids"],
  ["BELT", "Rubber loop that spins in the engine", "kids"],
  ["GEAR", "Cars shift into this to speed up", "kids"],
  ["PEDAL", "You press it with your foot", "kids"],
  ["RADIO", "It plays music in the car", "kids"],
  ["TOW", "To pull a broken-down car", "kids"],
  ["GAS", "Fuel you pump into the tank", "kids"],
  ["PUMP", "You fill the tank at one", "kids"],
  ["LIGHT", "It helps you see at night", "kids"],
  ["DOOR", "Open it to climb in", "kids"],
  ["WINDOW", "Glass you can roll down", "kids"],
  ["WASH", "What a muddy car needs", "kids"],
  ["SIREN", "Loud wail on a fire truck", "kids"],
  ["CONE", "Orange marker in the road", "kids"],
  ["MAP", "It shows you the way", "kids"],
  ["HONK", "Sound a horn makes", "kids"],
  ["SPARE", "The extra tire in the trunk", "kids"],
  ["BUMPER", "Bar across the front and back", "kids"],
  ["DRIVER", "The person behind the wheel", "kids"],
  ["MOTOR", "Another word for engine", "kids"],
  ["FUEL", "What the engine burns to go", "kids"],
  ["CAR", "What you drive", "kids"],
  ["BUCKLE", "Click it to fasten your seat belt", "kids"],
  ["PARK", "Stop here and turn the car off", "kids"],
  ["STOP", "What the red sign tells you to do", "kids"],
  ["GREEN", "Traffic light color that means go", "kids"],
  ["SPEED", "How fast you are going", "kids"],
  ["TANK", "Where the gas is stored", "kids"],
  ["WAGON", "Long car with room in the back", "kids"],
  ["RAMP", "Short road onto the highway", "kids"],

  /* ---------------- easy: familiar to anyone who owns a car ------------ */
  ["ALIGN", "Make all four wheels point true", "easy"],
  ["AXLE", "Shaft the wheels turn on", "easy"],
  ["BATTERY", "It supplies power before the engine starts", "easy"],
  ["CLUTCH", "Manual-transmission pedal", "easy"],
  ["COUPE", "Two-door body style", "easy"],
  ["DIESEL", "Fuel used by many work trucks", "easy"],
  ["FILTER", "It traps dirt in oil or air", "easy"],
  ["HYBRID", "Vehicle with electric and gas power", "easy"],
  ["PISTON", "It moves up and down inside a cylinder", "easy"],
  ["PLUG", "Spark ___", "easy"],
  ["RIM", "Metal center of a wheel", "easy"],
  ["ROTOR", "Disc squeezed by a brake caliper", "easy"],
  ["SEDAN", "Common four-door body style", "easy"],
  ["SIGNAL", "Blinker or traffic light", "easy"],
  ["SPARK", "Tiny flash that ignites fuel", "easy"],
  ["AIRBAG", "Inflatable cabin safety cushion", "easy"],
  ["EXHAUST", "System that routes spent gases away", "easy"],
  ["FENDER", "Body panel that arches over a wheel", "easy"],
  ["FUSE", "Small electrical protector designed to blow", "easy"],
  ["GASKET", "Seal between two joined surfaces", "easy"],
  ["GRILLE", "Front opening that admits cooling air", "easy"],
  ["MUFFLER", "It quiets the exhaust", "easy"],
  ["RADIATOR", "It helps keep the engine cool", "easy"],
  ["COOLANT", "Fluid that carries heat away from the engine", "easy"],
  ["DASHBOARD", "Panel holding gauges and controls", "easy"],
  ["DIPSTICK", "Rod used to check the oil level", "easy"],
  ["HEADLIGHT", "Forward lamp used after dark", "easy"],
  ["IGNITION", "System that starts combustion", "easy"],
  ["ODOMETER", "Gauge recording total distance traveled", "easy"],
  ["STARTER", "Electric motor that cranks the engine", "easy"],
  ["STRUT", "Structural suspension damper", "easy"],
  ["THERMOSTAT", "Valve that regulates coolant flow", "easy"],
  ["TURBO", "Exhaust-driven device that forces in more air", "easy"],
  ["VALVE", "It controls flow into or out of a cylinder", "easy"],
  ["WINDSHIELD", "Front glass that shields the occupants", "easy"],
  ["ALIGNMENT", "Adjustment of wheel angles", "easy"],
  ["BALANCE", "Wheel service that stops highway vibration", "easy"],
  ["TREAD", "Patterned surface that meets the road", "easy"],
  ["TRACTION", "Grip between tires and the road", "easy"],
  ["TORQUE", "Twisting force produced by an engine", "easy"],
  ["MILEAGE", "Distance traveled, or fuel economy", "easy"],
  ["OCTANE", "Gasoline's resistance-to-knock rating", "easy"],
  ["UNLEADED", "Gasoline type without added lead", "easy"],
  ["EMISSIONS", "Gases checked during an environmental test", "easy"],
  ["SENSOR", "Electronic part that measures a condition", "easy"],
  ["VOLTAGE", "Electrical potential measured in volts", "easy"],
  ["CHARGER", "Device that replenishes a battery", "easy"],
  ["ELECTRIC", "Powered solely by a battery and motor", "easy"],
  ["RANGE", "How far a vehicle goes before refueling", "easy"],
  ["PICKUP", "Truck with an open cargo bed", "easy"],
  ["MINIVAN", "Family vehicle known for sliding doors", "easy"],
  ["TRAILER", "Unpowered load carrier pulled behind", "easy"],
  ["HITCH", "Connection point for towing a trailer", "easy"],
  ["SUNROOF", "Movable panel above the cabin", "easy"],
  ["CONSOLE", "Storage and controls between the front seats", "easy"],
  ["SHIFTER", "Control used to select a gear", "easy"],
  ["NEUTRAL", "Gear position that disconnects drive", "easy"],
  ["REVERSE", "Gear used to back up", "easy"],
  ["MECHANIC", "Technician who inspects and repairs vehicles", "easy"],
  ["HEATER", "Cabin system that supplies warm air", "easy"],
  ["FLUID", "Liquid used for lubrication or hydraulics", "easy"],
  ["FRAME", "Structural foundation beneath a vehicle", "easy"],
  ["PULLEY", "Grooved wheel that carries a belt", "easy"],
  ["SPOILER", "Body piece that changes airflow at speed", "easy"],
  ["CHASSIS", "Vehicle's supporting frame and structure", "easy"],
  ["CYLINDER", "Engine chamber where a piston travels", "easy"],
  ["DEFROSTER", "It clears ice or fog from the glass", "easy"],
  ["ANTIFREEZE", "Cold-weather ingredient in coolant", "easy"],
  ["ALTERNATOR", "It charges the battery while the engine runs", "easy"],
  ["BEARING", "It lets a rotating part turn with less friction", "easy"],
  ["CALIPER", "It squeezes brake pads against a rotor", "easy"],
  ["WINCH", "Cable-winding device used for recovery", "easy"],
  ["CROSSOVER", "Car-based utility vehicle", "easy"],
  ["HATCHBACK", "Body style with a rear door that lifts", "easy"],
  ["ROADSTER", "Sporty open-top two-seater", "easy"],
  ["CONVERTIBLE", "Car with a roof that folds away", "easy"],
  ["HORSEPOWER", "Common measure of engine output", "easy"],
  ["MODULE", "Self-contained electronic control unit", "easy"],
  ["COMPUTER", "Module that manages vehicle systems", "easy"],
  ["WIRING", "Network of conductors behind the electrics", "easy"],
  ["CIRCUIT", "Complete path followed by current", "easy"],
  ["TERMINAL", "Battery connection point", "easy"],
  ["ETHANOL", "Alcohol commonly blended into gasoline", "easy"],
  ["NAVIGATION", "Dashboard system that gives route guidance", "easy"],
  ["SUSPENSION", "Springs and links between body and wheels", "easy"],
  ["TRANSMISSION", "It selects ratios between engine and wheels", "easy"],

  /* ---------------- advanced: shop-floor vocabulary -------------------- */
  ["CAMSHAFT", "Shaft that opens and closes engine valves", "advanced"],
  ["CRANKSHAFT", "It turns piston motion into rotation", "advanced"],
  ["DRIVESHAFT", "It carries rotation toward the driven wheels", "advanced"],
  ["FLYWHEEL", "Heavy disc that smooths engine power", "advanced"],
  ["MANIFOLD", "Engine passage that gathers or distributes flow", "advanced"],
  ["INJECTOR", "It sprays a measured amount of fuel", "advanced"],
  ["CARBURETOR", "Classic device that mixes fuel and air", "advanced"],
  ["SILENCER", "Another name for a muffler", "advanced"],
  ["INVERTER", "EV device that converts battery current", "advanced"],
  ["REGENERATIVE", "Braking that returns energy to a battery", "advanced"],
  ["SOLENOID", "Electromagnetic actuator", "advanced"],
  ["TENSIONER", "Spring-loaded part that keeps a belt tight", "advanced"],
  ["SERPENTINE", "Long belt winding around several accessories", "advanced"],
  ["INTERCOOLER", "It cools compressed air from a turbo", "advanced"],
  ["REFRIGERANT", "Heat-carrying chemical inside the A/C", "advanced"],
  ["DIFFERENTIAL", "Gearset letting drive wheels turn at different speeds", "advanced"],
  ["RESERVOIR", "Container that holds operating fluid", "advanced"],
  ["BOOSTER", "Brake part that multiplies pedal force", "advanced"],
  ["IDLER", "Free-spinning pulley that guides a belt", "advanced"],
  ["CASTER", "Steering-axis angle that helps a car track straight", "advanced"],
  ["CAMBER", "Inward or outward wheel tilt seen from the front", "advanced"],
  ["TOE", "Alignment angle comparing the fronts of two tires", "advanced"],
  ["RACK", "Toothed bar in a common steering system", "advanced"],
  ["RELAY", "Electrically controlled switch", "advanced"],
  ["DAMPER", "Part that controls unwanted suspension motion", "advanced"],
  ["SUBFRAME", "Bolt-on structure supporting drivetrain or suspension", "advanced"],
  ["CATALYST", "Material that speeds an emissions-cleaning reaction", "advanced"],
  ["CONVERTER", "Catalytic ___ in the exhaust system", "advanced"],
  ["DIAGNOSTIC", "Test process used to identify a fault", "advanced"],
  ["OVERDRIVE", "High gear that lowers cruising engine speed", "advanced"],
  ["LIFTGATE", "Powered or manual rear door on an SUV", "advanced"],
  ["MUDGUARD", "Shield that limits spray behind a wheel", "advanced"],
  ["FLOORBOARD", "Lower interior panel beneath the occupants", "advanced"],
  ["BLOWOUT", "Sudden and complete tire failure", "advanced"],
  ["ADVISOR", "Shop pro who explains recommended service", "advanced"],
  ["COIL", "Ignition part that raises voltage for a spark", "advanced"],
  ["COMPRESSOR", "Air-conditioning pump driven by belt or motor", "advanced"],
  ["CONDENSER", "A/C heat exchanger mounted near the radiator", "advanced"],
  ["TACHOMETER", "Gauge showing engine revolutions per minute", "advanced"],
  ["SPEEDOMETER", "Gauge that shows road speed", "advanced"],
  ["SIDEWALL", "Outer side surface of a tire", "advanced"],
  ["AUTOMATIC", "Transmission that shifts without a clutch pedal", "advanced"],
  ["CHARGING", "Adding electrical energy to a battery", "advanced"],
  ["HEADREST", "Seat support behind an occupant's head", "advanced"],
  ["ARMREST", "Padded cabin support beside a seat", "advanced"],
  ["BODYWORK", "Repair of exterior panels and collision damage", "advanced"],
  ["DEALERSHIP", "Franchised seller and servicer of a make", "advanced"],

  /* Abbreviations — the clue has to say so, or the answer looks wrong. */
  ["ABS", "Anti-lock braking system, in short", "advanced"],
  ["SUV", "Sport utility vehicle, in short", "advanced"],
  ["EGR", "Exhaust-gas recirculation, in short", "advanced"],
  ["TPMS", "Tire-pressure monitoring system, in short", "advanced"],

  /* Two words run together — the "(2 wds)" tag is added automatically. */
  ["WATERPUMP", "It circulates coolant through the engine", "advanced", 2],
  ["AIRFILTER", "It keeps dust out of the engine's intake", "advanced", 2],
  ["CABINFILTER", "It cleans air entering the passenger compartment", "advanced", 2],
  ["TIMINGBELT", "Toothed belt syncing crankshaft and camshaft", "advanced", 2],
  ["CONTROLARM", "Suspension link between wheel and frame", "advanced", 2],
  ["BALLJOINT", "Pivot connecting suspension and steering parts", "advanced", 2],
  ["HALFSHAFT", "Drive axle from differential to wheel", "advanced", 2],
  ["PARKINGBRAKE", "Brake that holds a stopped vehicle in place", "advanced", 2],
  ["POWERSTEERING", "Assisted system that makes turning easier", "advanced", 2],
  ["TRANSFERCASE", "Four-wheel-drive unit splitting power front and rear", "advanced", 2],
  ["SCANTOOL", "Electronic device used to read vehicle data", "advanced", 2],
  ["DOORHANDLE", "Lever pulled to enter the cabin", "advanced", 2],
  ["KEYFOB", "Pocket remote used to lock or start a car", "advanced", 2],
  ["LUGNUT", "Fastener that secures a wheel", "advanced", 2],
  ["HUBCAP", "Decorative cover over a wheel center", "advanced", 2],
  ["WHEELBASE", "Distance between front and rear axles", "advanced", 2],
  ["FOGLAMP", "Low-mounted light for poor visibility", "advanced", 2],
  ["TAILGATE", "Hinged rear panel of a pickup bed", "advanced", 2],
  ["TAILPIPE", "Visible outlet at the end of the exhaust", "advanced", 2],
  ["SEATBELT", "Strap that restrains an occupant", "advanced", 2],
  ["CVJOINT", "Flexible drive connection used near a wheel", "advanced", 2],
];

export const CLUE_BANK: ClueWord[] = CLUES.map(([answer, clue, level, words]) => ({
  answer,
  // Solvers need to know the answer is one run of letters, not two words.
  clue: words && words > 1 ? `${clue} (${words} wds)` : clue,
  level,
  ...(words ? { words } : {}),
}));

// Word-search words, tagged the same way. No clues here — the player is only
// hunting letters — so this stays a short tuple list.
const SEARCH: [string, ClueLevel][] = [
  ["OIL", "kids"], ["GAS", "kids"], ["CAR", "kids"], ["TOW", "kids"],
  ["KEY", "kids"], ["VAN", "kids"], ["BUS", "kids"], ["MAP", "kids"],
  ["TIRE", "kids"], ["HOOD", "kids"], ["HORN", "kids"], ["ROAD", "kids"],
  ["SEAT", "kids"], ["DOOR", "kids"], ["JACK", "kids"], ["BELT", "kids"],
  ["GEAR", "kids"], ["PARK", "kids"], ["STOP", "kids"], ["TANK", "kids"],
  ["PUMP", "kids"], ["WASH", "kids"], ["RAMP", "kids"], ["CONE", "kids"],
  ["WHEEL", "kids"], ["BRAKE", "kids"], ["TRUCK", "kids"], ["WIPER", "kids"],
  ["TRUNK", "kids"], ["MOTOR", "kids"], ["PEDAL", "kids"], ["SPARE", "kids"],
  ["ENGINE", "kids"], ["GARAGE", "kids"], ["MIRROR", "kids"], ["WAGON", "kids"],

  ["ALIGN", "easy"], ["AXLE", "easy"], ["CLUTCH", "easy"], ["FILTER", "easy"],
  ["PISTON", "easy"], ["ROTOR", "easy"], ["SPARK", "easy"], ["FUSE", "easy"],
  ["FENDER", "easy"], ["BUMPER", "easy"], ["AIRBAG", "easy"], ["GASKET", "easy"],
  ["GRILLE", "easy"], ["SENSOR", "easy"], ["RELAY", "easy"], ["SHOCK", "easy"],
  ["STRUT", "easy"], ["TREAD", "easy"], ["TURBO", "easy"], ["VALVE", "easy"],
  ["HITCH", "easy"], ["WINCH", "easy"], ["PICKUP", "easy"], ["PULLEY", "easy"],
  ["OCTANE", "easy"], ["COOLANT", "easy"], ["EXHAUST", "easy"], ["MILEAGE", "easy"],
  ["REVERSE", "easy"], ["VOLTAGE", "easy"], ["CHASSIS", "easy"], ["SUNROOF", "easy"],

  ["CALIPER", "advanced"], ["BEARING", "advanced"], ["DAMPER", "advanced"],
  ["CAMBER", "advanced"], ["CASTER", "advanced"], ["KEYFOB", "advanced"],
  ["LUGNUT", "advanced"], ["SHIFTER", "advanced"], ["STARTER", "advanced"],
  ["INJECTOR", "advanced"], ["TAILPIPE", "advanced"], ["MANIFOLD", "advanced"],
  ["SOLENOID", "advanced"], ["FLYWHEEL", "advanced"], ["CAMSHAFT", "advanced"],
];

export const SEARCH_WORDS: { word: string; level: ClueLevel }[] = SEARCH.map(
  ([word, level]) => ({ word, level }),
);

// A mode plays its own level plus the easier ones below it, so "Advanced"
// still mixes in familiar words instead of being wall-to-wall jargon.
export const LEVELS_FOR: Record<ClueLevel, ClueLevel[]> = {
  kids: ["kids"],
  easy: ["kids", "easy"],
  advanced: ["easy", "advanced"],
};
